### PR TITLE
Add PluginNumberFormat

### PR DESCRIPTION
**Pull request by WebsiteDeveloper**

### CODE REVIEW

**Comment by emulienfou** [comment]
Hi @WebsiteDeveloper thanks to contributing to the Dwoo core, however `number_format` function is listed in the allowed PHP native functions in `Dwoo\Security\Policy` class.

To do so, you don't need to create a custom plugin like you did!
You can just need to call the PHP function such as:
```
{number_format $foo 2 "," " "}
```

**Comment by WebsiteDeveloper** [comment]
Alright somehow i didn't find this in the docs :)
But thanks anyway

**Comment by emulienfou** [comment]
You're write, this is a missing information in the official documentation.
This will be added ASAP.

Best regards

**Comment by emulienfou** [comment]
Official documentation added:
* http://dwoo.org/documentation/v1.3/dwoo-for-designers.html#php-native-functions
* http://dwoo.org/documentation/v1.3/extending-dwoo.html#allowdisallow-php-native-functions

**Pull request closed without merging**
